repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: debug-statements

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.5
  hooks:
    - id: ruff-format
      files: app/
      exclude: ^app/alembic
      fail_fast: true
    - id: ruff
      files: app/
      exclude: ^app/alembic
      args: [ --select, I, --fix ]
      fail_fast: true

- repo: local
  hooks:
  - id: test
    name: Run Tests
    entry: inv ci
    language: system
    always_run: true
    pass_filenames: false
    fail_fast: true
    verbose: true