version: '3.8'


services:
  api:
    build:
      context: .
    container_name: quoteflix-api
    env_file: .env
    command: uvicorn api.main:app --reload --host 0.0.0.0
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
