services:
  motoserver:
    image: motoserver/moto:3.1.1
    ports:
      - '5000:5000'
    environment:
      - MOTO_PORT=5000
  
  test-db:
    image: postgres:16-alpine
    env_file:
      - .env.test
    environment:
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
      - POSTGRES_USER=${TEST_POSTGRES_USER}
    ports:
      - '5433:5432'
    depends_on:
      - motoserver
  
  api-test:
    restart: no
    depends_on:
      - test-db
      - motoserver
    env_file:
      - .env.test
    volumes:
      - ./app/:/app/
    build:
      context: .
      args:
        - INSTALL_DEV=${INSTALL_DEV-true}
    command: echo "noop"

volumes:
  test_db_data: