services:
  api:
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=80
    build:
      context: .
      args:
        - INSTALL_DEV=${INSTALL_DEV-false}
    command: /start.sh

volumes:
  app-db-data:
