services:
  api:
    restart: unless-stopped
    container_name: quoteflix-api
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=80
    build:
      context: .
      args:
        - ENVIRONMENT=${ENVIRONMENT-local}
    command: /start.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis-db-data:
