[tool.poetry]
name = "api"
version = "0.1.0"
description = "The API for Quoteflix platform"
authors = ["Aleksandr Sosedskyi <sanya1sosedskiy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"

[tool.poetry.group.dev.dependencies]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
