"""Update PhraseIssue Model

Revision ID: 11bd16767b19
Revises: 4f6d735a7d73
Create Date: 2024-05-29 18:40:06.387733

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11bd16767b19"
down_revision: Union[str, None] = "4f6d735a7d73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("phrases_issues", sa.Column("issuer_ip", sa.String(), nullable=False, server_default="lorem ipsum"))
    op.alter_column("phrases_issues", "issuer_ip", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phrases_issues", "issuer_ip")
    # ### end Alembic commands ###
