"""Update PhraseIssue Model

Revision ID: 27de525a20ff
Revises: 11bd16767b19
Create Date: 2024-05-29 20:18:40.767818

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27de525a20ff"
down_revision: Union[str, None] = "11bd16767b19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("phrases_issues", sa.Column("is_active", sa.Boolean(), nullable=False, server_default="True"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phrases_issues", "is_active")
    # ### end Alembic commands ###
