"""Update PhraseIssue Model

Revision ID: 5075c81f5ddc
Revises: aacca5ec4785
Create Date: 2024-05-29 18:26:20.576061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5075c81f5ddc'
down_revision: Union[str, None] = 'aacca5ec4785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
