"""Create index for column normalized_text

Revision ID: 57e34e451984
Revises: 27de525a20ff
Create Date: 2024-06-02 12:20:03.512966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e34e451984'
down_revision: Union[str, None] = '27de525a20ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_phrases_normalized_text'), 'phrases', ['normalized_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrases_normalized_text'), table_name='phrases')
    # ### end Alembic commands ###
