"""Update PhraseIssue Model

Revision ID: 6036ee9945b3
Revises: 99d2a4ff3726
Create Date: 2024-05-29 18:20:24.386708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6036ee9945b3'
down_revision: Union[str, None] = '99d2a4ff3726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrases_issues',
    sa.Column('phrase_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('phrase_issue_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrase_issue_reports',
    sa.Column('phrase_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], name='phrase_issue_reports_phrase_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='phrase_issue_reports_pkey')
    )
    op.drop_table('phrases_issues')
    # ### end Alembic commands ###
