"""Add Phrase Issue Report model

Revision ID: 9f15ee426e00
Revises: 91ad43a14d24
Create Date: 2024-05-28 20:55:44.707629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f15ee426e00'
down_revision: Union[str, None] = '91ad43a14d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
