"""Add Movie model

Revision ID: c3c504729762
Revises: 4121b6d31b89
Create Date: 2024-03-21 12:21:17.217442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_storages.integrations.sqlalchemy
from fastapi_storages import FileSystemStorage

# revision identifiers, used by Alembic.
revision: str = "c3c504729762"
down_revision: Union[str, None] = "4121b6d31b89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "PROCESSED", "ERROR", name="moviestatus"),
            nullable=False,
        ),
        sa.Column(
            "file",
            fastapi_storages.integrations.sqlalchemy.FileType(
                FileSystemStorage(path="movies/")
            ),
            nullable=True,
        ),
        sa.Column(
            "subtitles_file",
            fastapi_storages.integrations.sqlalchemy.FileType(
                FileSystemStorage(path="subtitles/")
            ),
            nullable=True,
        ),
        sa.Column("language", sa.Enum("EN", name="languages"), nullable=False),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movies")
    # ### end Alembic commands ###
