name: Build and tests
run-name: ${{ github.actor }} runs build and tests
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Setup environment
      run: cp .env.test .env

    - name: Build
      run: docker compose -f docker-compose.tests.yaml build

    - name: Test
      run: docker compose -f docker-compose.tests.yaml run --rm api-test pytest --cov --cov-fail-under=90
