name: Run checks (flake8, mypy, black, isort) and tests
run-name: ${{ github.actor }} runs checks and tests
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Setup environment
      run: cp .env.test .env

    - name: Test docker build
      run: poetry run inv build

    - name: Run Tests
      run: poetry run inv tests
