name: deploy-to-dev
run-name: Deploy to development
on:
  workflow_dispatch:
    

jobs:
  deploy_to_dev:
    name: Deploy to development server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run
        uses: appleboy/ssh-action@v1.0.3
        with:
          context: .
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            cd /var/www/quoteflix-api/
            git fetch
            echo "123 ${GITHUB_SHA}"
            git reset --hard ${GITHUB_SHA} --verbose
            export USERNAME=${{ secrets.TRAEFIK_USERNAME }}
            export PASSWORD=${{ secrets.TRAEFIK_PASSWORD }}
            export HASHED_PASSWORD=$(openssl passwd -apr1 $PASSWORD)
            cp /var/www/environment/.env /var/www/quoteflix-api/.env
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up --remove-orphans -d --build --force-recreate