name: deploy-to-dev
run-name: Deploy to development
on:
  workflow_dispatch:
    

jobs:
  deploy_to_dev:
    name: Deploy to development server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run
        uses: appleboy/ssh-action@v1.0.3
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_KEY }}
          port: ${{ secrets.DEV_PORT }}
          envs: SHA
          script_stop: true
          script: |
            cd /var/www/flickphrase-api/
            echo "$SHA"
            eval `ssh-agent -s`
            ssh-add ~/.ssh/pet
            git fetch
            git reset --hard $SHA
            export USERNAME='${{ secrets.TRAEFIK_USERNAME }}'
            export PASSWORD='${{ secrets.TRAEFIK_PASSWORD }}'
            export HASHED_PASSWORD=$(openssl passwd -apr1 ${PASSWORD})
            cp /var/www/environment/.env.backend /var/www/flickphrase-api/.env
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml down --rmi all
            docker network inspect traefik-public  >/dev/null 2>&1 || docker network create traefik-public
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up  -d --build --force-recreate