name: Deploy to Dev

on:
  push:
    branches:
      - test-deploy
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: configure aws credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::305439215774:role/quoteflix-deploy
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      # - name: Build, tag, and push image to Amazon ECR
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_TAG: ${{ github.sha }}
      #     ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #     echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: "3.74.158.111"
          username: "ubuntu"
          key: -----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
              NhAAAAAwEAAQAAAgEAqVL3FBVWqeDQyzmwoIro9M+TJI7BaxTVtdLVSWBNzltypA83Uehv
              /9cQjwLckykDoVRKnUpZsol0Tm50qYEbYfXpvOMMw7VSTHDz/GM8mBIpNHUB4ROq2OqVE3
              6oGAI4E1M/eRo6uZPLTjEgVFdfhbKU+gAi2b2JcLJm6RqvOyX8TVdKRxOJ0bOfpv6t76un
              i4OwZxLtrFXjVl7fHVFxV95LSsSDRqWN5mdZkmPLFUgx1zjnKLoqHF2Q5Gn4DgZqR3otlh
              JMk3BbewxTRZflzWdTX+YmnmPiGIROS8NJnr7ctKQGmq8ysfMm7Eru8UKLhQpCIbFKumhf
              EtAfXpaYbJXzEdHrTtRY2q6SCO46vJBemgsgg8aem0+IgzpSR7zVVeU50pIRNOmpfTwPUA
              Awe+mEU3//PZsXpuoS0H8zW40YLHlRUABLEHxyIH/beG5dTzGWPViF2s5o+eIIbrul91Rv
              w4HPqPILyOD/AHJsPZvHOOnbAEoR57GAGIErfX0ETSJsGIA95Th1BPe8xfyzMSpxj30D4E
              wD1CzORJ+UGl8iHD+4AUokA1rmZz1F/h01kAdV8v36PIbohVR/UF+m/pIjQekcVoyMb3EO
              cb1Qz6eTBtwwkcAlKPRxucP1oEm1XWLrT0ymsWBI2O7j5p0q3Ktta9msz18jUjaZw/fAdO
              8AAAdQdbO/JnWzvyYAAAAHc3NoLXJzYQAAAgEAqVL3FBVWqeDQyzmwoIro9M+TJI7BaxTV
              tdLVSWBNzltypA83Uehv/9cQjwLckykDoVRKnUpZsol0Tm50qYEbYfXpvOMMw7VSTHDz/G
              M8mBIpNHUB4ROq2OqVE36oGAI4E1M/eRo6uZPLTjEgVFdfhbKU+gAi2b2JcLJm6RqvOyX8
              TVdKRxOJ0bOfpv6t76uni4OwZxLtrFXjVl7fHVFxV95LSsSDRqWN5mdZkmPLFUgx1zjnKL
              oqHF2Q5Gn4DgZqR3otlhJMk3BbewxTRZflzWdTX+YmnmPiGIROS8NJnr7ctKQGmq8ysfMm
              7Eru8UKLhQpCIbFKumhfEtAfXpaYbJXzEdHrTtRY2q6SCO46vJBemgsgg8aem0+IgzpSR7
              zVVeU50pIRNOmpfTwPUAAwe+mEU3//PZsXpuoS0H8zW40YLHlRUABLEHxyIH/beG5dTzGW
              PViF2s5o+eIIbrul91Rvw4HPqPILyOD/AHJsPZvHOOnbAEoR57GAGIErfX0ETSJsGIA95T
              h1BPe8xfyzMSpxj30D4EwD1CzORJ+UGl8iHD+4AUokA1rmZz1F/h01kAdV8v36PIbohVR/
              UF+m/pIjQekcVoyMb3EOcb1Qz6eTBtwwkcAlKPRxucP1oEm1XWLrT0ymsWBI2O7j5p0q3K
              tta9msz18jUjaZw/fAdO8AAAADAQABAAACADgW7RUAipBEkjW32wwbZ9bsyfvStDyyDqcn
              +5JObge9IEk7ZyJhYnR3/Bq7onC3JeYzw3G+Nt9fDCGNEmUyCO2W5gI1nj1YW7ZJtnD1OJ
              XRckfXuLMj7jTj5FUsYCdv2L6CFaUarLhbvn2c5W468UAbK6FzGRhS4mvsFQ4D0mdACode
              MpM/5CgMngbWF60sihg7m9xRF10+qEusqrEOEQM/9mYCmc/1uH9J3hCRsSzQGP6H8X76yE
              dUMVKQzeRreJpL3Tz4u9gdYJhuuUj06+FyaFp8pW9TfAqODVeojcMhy3+lVDC6d4seFlcw
              7V0LI6eDAewiTDRarZ/QRIvzS/Ml4NHPJ1jonktBeJ3aEi5GwbGz/vuecMUl3taEyWp+iE
              bdOkD7DXwAtyOqidXcNJI2629PQIuEII2O+qfCDQpiaUHehmNwaITElVRkqhi11ZxCByrq
              GE4CC5FNSzpg+NOgtsb01cAz5vcV+jaYCNS3uJDPA11og0ZVbqPhxtUkGc/KPQ+m1gRw9N
              dXroZ9LsG+Eg1OcvwtiLpwV9jAgvh58Jlwr6kDJ6dpwneM5SmT+a0CTPQnbo/Q6IwXHLpD
              umgLLiSCAT0ytGhFwSfPpwhwFlJ6HOP4vLoKA3j7QsZ0V5aNsZYAipR/qRzHWUW2w3aGXM
              Pm+OGrMr47rBDJRcCJAAABAHwIsK4dUlinwm9swTevdi9mZedTnRT83Ox5x8OW/2a32rqZ
              XzXzEWddSgkxLoL1Atyqp+sk9Ja1qGgy87xvFORV30YpU9XzTkCdwVGiZ2iWXFfJCiXD0D
              RSOyUAaPh5PggKLABL8WwUOxy5vyNU4v42GIrnUmTRXGj5FEWTQbvq+x8xkbvfV4hrcQ4E
              k5rYhViq/CZcWI9OqQrAagDFKK/MMFJKoPy5igOzsGbw4bssnOli69CL8XksR3lVYTo6Qt
              wig6NZFvScPRvhOObF3V8MY3zpPxZoCE6c9aqMWEcZUNKC+m8IKeukiKBrk8I/wS9gfbye
              r4YHNf36CIT+Ki8AAAEBAOSZ+5eCyaA0nAV36IqgM2U2+Nk09qAA6WjQMCMPXj0skSQLId
              OvPhVaRpI44AqsKevHf7aY8rgYUdRvw8TY4fA37SYyqhx3+G/qHKnCLWbHwHuSLQ3kol3o
              GhzZpgUT+LjBc7hEWBtI+MCBh/VpQdbODxqtOxpG6i8aEWObv8yGKjcjScaEAyf8qdi3X9
              WfDSIFIDOlkxPH7q0M3UUDK2mc3zC0J32Uk+exzX0uV/VpFnnkXDBCHtE+05Hltkga7ET9
              bEmY5q/teMjEMhQxIep6UV4IMykMSEpb9tJoV7D5eXU3TeCKtOj/X49JNgvOkzoKQU2dDZ
              qU13nnhJYw/skAAAEBAL2eNzR7HZ3a6U5wsbfgFNQnOq2p9+lJZ3ZObVsyPyCeKzE6sTk6
              HLoI9rH65MtfcQcrZJjY8ZVT/cmU1+cl4hdUPh/cyKfGIeNjOtow1mIdM1msS8F/Rpj9mE
              JETXLB7x5nLgyAx3Qcx9+GKRto2KhtX7Q7Www1TDCFRejEDraqmwhUfSYug+MjWWk669ZA
              vsI70sa7eylOao9Y3apRt13L/43BS0I4Oe1EQb3qCyQiYVf6mIbOFnCuTJgV+W/zR0U0IV
              COg2JdipZHS0KqDTq87LK6ct181HBnaO0P3c/nFH2ovGVZ+4gT3jnByp8507mHIP+mZiL1
              g3PS2mhRGfcAAAAUc3VzaWRza3lpQGdvb2dsZS5jb20BAgMEBQYH
              -----END OPENSSH PRIVATE KEY-----
          script: |
            export EC2_PROJECT_PATH="/home/ubuntu/quoteflix-api"
            export DEBUG_LOGS=true
            export ENVIRONMENT=dev
            export SECRET="1Dv6+GCuYU:zW,W2{SlS<u*0[~grCo"
            export MOVIES_S3_PATH="movies/"
            export INSTALL_DEV=false
            export DOMAIN="phraseqwe.space"
            export IMAGE_NAME=305439215774.dkr.ecr.eu-central-1.amazonaws.com/quoteflix-api:5c05f559a68a417ae9a2f072d8a4f7923baf5af2
            export MAX_FFMPEG_WORKERS=20
            export SCENES_TMP_PATH="/tmp/scenes"
            export PHRASES_PAGE_SIZE=3

            # S3
            export S3_ENDPOINT_URL="http://minio:9000"
            export S3_BUCKET="flickphrase"
            export S3_ACCESS_KEY="${{ secrets.S3_ACCESS_KEY }}"
            export S3_SECRET_KEY="${{ secrets.S3_SECRET_KEY }}"
            export S3_REGION_NAME="weur"

            # Database
            export DATABASE_URL="postgresql+asyncpg://flickphrase:flickphrase@host.docker.internal:5432/flickphrase"
            export POSTGRES_PASSWORD="flickphrase"
            export POSTGRES_USER="flickphrase"
            export POSTGRES_DB="flickphrase"

            # Database test
            export TEST_DATABASE_URL="postgresql+asyncpg://flickphrase-test:flickphrase@test-db:5432/flickphrase-test"
            export TEST_POSTGRES_PASSWORD="flickphrase"
            export TEST_POSTGRES_USER="flickphrase-test"
            export TEST_POSTGRES_DB="flickphrase-test"

            # Traefik
            export USERNAME="admin"
            export PASSWORD="CfP!N+xqzEH\\6\\S30V[9"
            export EMAIL="susidskyi@gmail.com"
            export STACK_NAME="local-flickphrase-com"
            export ROBOTS_HEADER="noindex, nofollow"

            # Logfire
            export LOGFIRE_TOKEN="${{ secrets.LOGFIRE_TOKEN }}"

            # Redis
            export REDIS_PASSWORD="ghpS9irRXK27ML5"
            export REDIS_API_CACHE_URL="redis://:ghpS9irRXK27ML5@redis:6379"

            # Admin
            export ADMIN_PANEL_PATH="/api/admin-dl94t1rt572w6ijqsbsu/"

            cd ${EC2_PROJECT_PATH}
            git fetch origin test-deploy
            git reset --hard origin/test-deploy
            docker pull 305439215774.dkr.ecr.eu-central-1.amazonaws.com/quoteflix-api:5c05f559a68a417ae9a2f072d8a4f7923baf5af2
            docker stop quoteflix-api quoteflix-traefik quoteflix-redis || true
            docker rm quoteflix-api quoteflix-traefik quoteflix-redis || true
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up